'use client';

import React from 'react';
import './globals.css';
import { ThemeProvider, createTheme } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import ReduxProvider from '@/redux/provider';

export const metadata = {
  title: 'Hushlee',
  description: 'Generated by create next app',
};

function RootLayout({ children }: { children: React.ReactNode }) {
  const darkMode = true;
  const darkTheme = createTheme({
    palette: { mode: darkMode ? 'dark' : 'light' },
  });

  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={darkTheme}>
          <CssBaseline />
          <ReduxProvider>{children}</ReduxProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

export default RootLayout;
