import React from "react";
import "./globals.css";
import ReduxProvider from "@/redux/provider";

export const metadata = {
  title: "Hushlee",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="m-0">
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}

export default RootLayout;
